name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
        
      - name: Build app
        run: ./mvnw package

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./src/main/docker/Dockerfile.jvm
          push: true
          tags: jb4adopt/adopt-test:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Trigger Azure WebHook
        run: 'curl "https://%24test-2-fml:$AZURE_WEBAPP_MASTER_PASSWORD@test-2-fml.scm.azurewebsites.net/docker/hook" -X POST --data "{}" --header "Content-Type: application/json" -v'
